[build]
  publish = "build"
  command = "npm run build"

[context.production]
  environment = { NODE_VERSION = "18" }

[context.deploy-preview]
  command = "npm run build:preview"

[context.branch-deploy]
  command = "npm run build:branch"
